git:
  depth: 5

language: node_js
node_js: 6

before_install:
  - npm config set spin false --global

cache:
  directories:
    - ~/.npm

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master

env:
  global:
  - secure: "DREp9PcuZE6OWJPZx68ponPgp1x9HPOV0FMCJ6jhh9VzPhA3Een3+UK6vgn3dPJjK2TdE+DrBhlLEQiaQAkvIi3W1b9zn67357hBDI59VWMmX9rPv/8tke2UFXptzDCKaFrx9qcJ2hTcrSaFe+V6zj8nQZrl7t9DZgF/aKq3sc0="
